### ISSUE TITLE
HTTPClient::ReceiveTimeoutError: execution expired

### ISSUE THREAD

**Issue by kidlab** [CodementorIO/rest-firebase#1]
We are using RestFirebase 0.9.5, experiencing many `HTTPClient::ReceiveTimeoutError` on our production, although we already set the `timeout` to 30s. It does not always happen but quite often in around 2 weeks.

Here is the backtrace:

```
/usr/lib64/ruby/2.0.0/openssl/buffering.rb:54 in "sysread"
/usr/lib64/ruby/2.0.0/openssl/buffering.rb:54 in "fill_rbuff"
/usr/lib64/ruby/2.0.0/openssl/buffering.rb:201 in "gets"
/gems/httpclient-2.4.0/lib/httpclient/session.rb:352 in "gets"
/gems/httpclient-2.4.0/lib/httpclient/session.rb:881 in "block in parse_header"
/gems/httpclient-2.4.0/lib/httpclient/session.rb:877 in "parse_header"
/gems/httpclient-2.4.0/lib/httpclient/session.rb:860 in "read_header"
/gems/httpclient-2.4.0/lib/httpclient/session.rb:667 in "get_header"
/gems/httpclient-2.4.0/lib/httpclient.rb:1141 in "do_get_header"
/gems/httpclient-2.4.0/lib/httpclient.rb:1090 in "do_get_block"
/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/httpclient.rb:34 in "block in do_get_block_with_newrelic"
/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/cross_app_tracing.rb:45 in "tl_trace_http_request"
/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/httpclient.rb:33 in "do_get_block_with_newrelic"
/gems/httpclient-2.4.0/lib/httpclient.rb:891 in "block in do_request"
/gems/httpclient-2.4.0/lib/httpclient.rb:985 in "protect_keep_alive_disconnected"
/gems/httpclient-2.4.0/lib/httpclient.rb:890 in "do_request"
/gems/httpclient-2.4.0/lib/httpclient.rb:778 in "request"
/gems/rest-core-3.3.3/lib/rest-core/engine/http-client.rb:25 in "request_sync"
/gems/rest-core-3.3.3/lib/rest-core/engine/http-client.rb:17 in "request"
/gems/rest-core-3.3.3/lib/rest-core/engine.rb:11 in "block in call"
/gems/rest-core-3.3.3/lib/rest-core/promise.rb:71 in "call"
/gems/rest-core-3.3.3/lib/rest-core/promise.rb:71 in "block (2 levels) in defer"
/gems/rest-core-3.3.3/lib/rest-core/promise.rb:140 in "block in synchronized_yield"
/gems/rest-core-3.3.3/lib/rest-core/promise.rb:140 in "synchronize"
/gems/rest-core-3.3.3/lib/rest-core/promise.rb:140 in "synchronized_yield"
```

Any thought?

**Comment by kidlab** [comment]
@godfat Do you configure `pool_size` in your application? And is there any relation between the `pool_size` and timeout error? We currently set `pool_size = 100` in our application, and it seems the problem still there.

**Comment by godfat** [comment]
@kidlab For rest-firebase, we didn't set any `pool_size`, therefore a new thread would be spawned each time we make a request. Indeed the lower number of `pool_size`, the higher chances you would see timeout. Consider:

``` ruby
RestFirebase.pool_size = 1
f = RestFirebase.new(:timeout => 10)
f.get('/'){ |r| puts r }
f.get('/'){ |r| puts r }
```

Suppose Firebase never responds, then after 10 seconds, both would get a timeout error but only one request was made. The second request spent 10 seconds while sitting in the queue, and cancelled after timeout.

FWIW, we also see timeout from Firebase a few times each day. We use the default 10 seconds timeout. There's another exception troubles me more. This might be off topic, but have you seen this before? I am wondering if this is a network issue because I couldn't reproduce this by retrying.

> RestFirebase::Error::BadRequest: [400] {"error"=>"Invalid data; couldn't parse JSON object. Are you sending a JSON object with valid key names?"}

**Comment by kidlab** [comment]
@godfat I haven't got exactly the same error like you so far, but I believe we encountered some kind of error saying "Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]" before, when we used the Firebase javascript SDK.

**Comment by godfat** [comment]
Thanks. We did see that before, too. Namely we'd `.` in the name, and later we translated it to `^` (which I regretted, should use `~` instead, but too late...)

Thanks I'll check again for those error.
