### ISSUE TITLE
Firebase SDK compatibility

### ISSUE THREAD

**Issue by mark-ellul** [CodementorIO/rest-firebase#13]
Hi,

Is this library compatible with the latest SDK 3.0.5?

Regards

Mark

**Comment by godfat** [comment]
This library uses REST API, and it has nothing to do with SDK I think.

**Comment by mark-ellul** [comment]
Thanks @godfat I just wanted to know if the gem still usable in projects now.

**Comment by godfat** [comment]
@mark-ellul I think so, but you might want to look into #12. It could be a blocker, but I don't know :o
