### ISSUE TITLE
Error: RestBuilder::Promise: ERROR: undefined method `itself

### ISSUE THREAD

**Issue by zohaib-sarwar-confiz** [CodementorIO/rest-firebase#16]
I am getting this error message

> RestBuilder::Promise: ERROR: undefined method `itself

**Error traces:**
from ["/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-builder-0.9.1/lib/rest-builder/client.rb:169:in `call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-builder-0.9.1/lib/rest-builder/client.rb:169:in`block in request_full'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/retry.rb:31:in `call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/retry.rb:31:in`process'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/retry.rb:15:in `block in call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/follow_redirect.rb:18:in`call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/follow_redirect.rb:18:in `process'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/follow_redirect.rb:11:in`block in call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/error_handler.rb:15:in `block in call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/error_detector.rb:10:in`block in call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/json_response.rb:26:in `block in call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/common_logger.rb:13:in`block in call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/cache.rb:34:in `block in app_call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/promise_pool-0.9.0/lib/promise_pool/promise.rb:118:in`call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/promise_pool-0.9.0/lib/promise_pool/promise.rb:118:in `block in resolve'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/promise_pool-0.9.0/lib/promise_pool/promise.rb:118:in`each'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/promise_pool-0.9.0/lib/promise_pool/promise.rb:118:in `inject'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/promise_pool-0.9.0/lib/promise_pool/promise.rb:118:in`resolve'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/promise_pool-0.9.0/lib/promise_pool/promise.rb:109:in `fulfilling'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/promise_pool-0.9.0/lib/promise_pool/promise.rb:84:in`block in fulfill'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/promise_pool-0.9.0/lib/promise_pool/promise.rb:84:in `synchronize'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/promise_pool-0.9.0/lib/promise_pool/promise.rb:84:in`fulfill'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/promise_pool-0.9.0/lib/promise_pool/promise.rb:136:in `protected_yield'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/promise_pool-0.9.0/lib/promise_pool/promise.rb:49:in`block in defer'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-builder-0.9.1/lib/rest-builder/engine.rb:28:in `call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/cache.rb:29:in`app_call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/cache.rb:25:in `call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/common_logger.rb:12:in`call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/json_response.rb:24:in `call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/error_detector.rb:8:in`call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/error_handler.rb:8:in `call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/follow_redirect.rb:11:in`call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/timeout.rb:16:in `process'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/timeout.rb:11:in`call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/retry.rb:15:in `call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/json_request.rb:13:in`call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/default_query.rb:8:in `call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/default_headers.rb:8:in`call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-core-4.0.0/lib/rest-core/middleware/default_site.rb:14:in `call'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-builder-0.9.1/lib/rest-builder/client.rb:168:in`request_full'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-builder-0.9.1/lib/rest-builder/client.rb:163:in `request'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-firebase-1.1.0/lib/rest-firebase.rb:87:in`request'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/rest-builder-0.9.1/lib/rest-builder/client.rb:102:in `get'", 
"(irb):1:in`irb_binding'", 
"/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb/workspace.rb:86:in `eval'", 
"/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb/workspace.rb:86:in`evaluate'", 
"/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb/context.rb:380:in `evaluate'", 
"/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb.rb:492:in`block (2 levels) in eval_input'", 
"/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb.rb:624:in `signal_status'", 
"/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb.rb:489:in`block in eval_input'",
 "/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb/ruby-lex.rb:247:in `block (2 levels) in each_top_level_statement'", 
"/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb/ruby-lex.rb:233:in`loop'", 
"/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb/ruby-lex.rb:233:in `block in each_top_level_statement'", 
"/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb/ruby-lex.rb:232:in`catch'",
 "/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb/ruby-lex.rb:232:in `each_top_level_statement'", 
"/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb.rb:488:in`eval_input'", 
"/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb.rb:397:in `block in start'",
 "/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb.rb:396:in`catch'",
 "/home/ubuntu/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/irb.rb:396:in `start'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/railties-3.2.18/lib/rails/commands/console.rb:47:in`start'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/railties-3.2.18/lib/rails/commands/console.rb:8:in `start'", 
"/home/ubuntu/.rvm/gems/ruby-2.1.2@rails-3.2.18/gems/railties-3.2.18/lib/rails/commands.rb:41:in`<top (required)>'", 
"script/rails:6:in `require'", "script/rails:6:in`<main>'"]

**My code is :**
@firebase = RestFirebase.new :site => 'https://appname-2088d.firebaseio.com/',
:timeout => 20, :max_retries => 3, :retry_exceptions => [IOError, SystemCallError, Timeout::Error], :auth_ttl => 82800, :auth => 'WbczLo249OaRXvqtSwMzW8S5wtfLd1YQZ*****

Can any know that wrong here.

Thanks

**Comment by godfat** [comment]
You should upgrade your Ruby to at least 2.2, which introduced `itself` method.
