### ISSUE TITLE
event source returns whole list instead of triggered data

### ISSUE THREAD

**Issue by VishalTaj** [CodementorIO/rest-firebase#18]
Hello,
i am using this gem to stream over my firebase for my chat applicationin order to do some business logic. before when some event triggers at the firebase @on.message method gaved me data as

`{
"path":"/location/to/messages",
 "data":{
"user_id":"xxx",
"message":"testing","type":"text"}
}`

but now when something triggers at the firebase it is returning whole chat list inside data and path as "/"

**Comment by godfat** [comment]
I think this depends on how you put the data. Did you put the whole
chat list to "/"? Otherwise it's probably a change from firebase
server.

**Comment by VishalTaj** [comment]
No, i'm just pinging a post request to firebase sub location.

**Comment by godfat** [comment]
What do you mean by pinging?

**Comment by godfat** [comment]
Then I have no idea :( This is fully depending on Firebase server. The
client didn't really do anything here.

**Comment by VishalTaj** [comment]
@godfat Thanks anyways :(

**Comment by godfat** [comment]
No problems. Let me know if you find there's anything the client could do.
